### ISSUE TITLE
why use weight norm?

### ISSUE THREAD

**Issue by gaopengcuhk** [locuslab/deq#1]

**Comment by jerrybai1995** [comment]
Hi @gaopengcuhk,

Weight normalization is not necessary. You can take it out by not using the `--wnorm` flag in the shell scripts. We just empirically found it a useful regularization that stabilizes the convergence to a fixed point (more specifically, using WN seems to help slow down the rate at which the # of Broyden iterations in forward/backward passes grow, which we discussed in the paper). This would thus be more efficient when you don't use the max iteration limit threshold, but instead an epsilon threshold for the DEQs.

Hope this helps.

**Comment by gaopengcuhk** [comment]
Thank you for your quick reply. I will send you a email discuss normalization problem in weight tied network.
