### ISSUE TITLE
Segmentation fault after removing hook

### ISSUE THREAD

**Issue by tesfaldet** [locuslab/deq#15]
Already created the issue here: https://github.com/pytorch/pytorch/issues/66037. Creating an issue here since it's relevant to this repo and for others who may come across the same issue.

A compromised solution is given in my "minimal working example."

**Comment by tesfaldet** [comment]
Apparently this has been fixed in the latest nightly build. However, this issue should remain open until the latest stable release contains the fix https://github.com/pytorch/pytorch/issues/66037#issuecomment-934034170

**Comment by tesfaldet** [comment]
https://github.com/pytorch/pytorch/releases/tag/v1.10.0 Pytorch 1.10 has been released, which includes the above fix. This issue can be closed.

**Comment by shaojieb** [comment]
@tesfaldet Thanks so much for tracking this issue! I've also been closely following it and am really excited that PyTorch 1.10 has fixed this :-)
