### ISSUE TITLE
DEQ for Vision Transformer

### ISSUE THREAD

**Issue by wyvernbai** [locuslab/deq#18]
Since the DEQ tech has achieved performance competitive with the state-of-the-art deep networks on Transformer based LM and CNN-based Image Recognition tasks, do the authors have plans to adapt DEQ for vision transformer architecture?

**Comment by shaojieb** [comment]
Hi @wyvernbai ,

Thanks for the question. I have thought about it but never got my hands on it.

**Comment by wyvernbai** [comment]
Thanks for your reply.
