### ISSUE TITLE
TrellisNetDEQModule class inheritence

### ISSUE THREAD

**Issue by kevinliang888** [locuslab/deq#8]
Hi, I noticed that in deq_trellisnet_module.py, you wrote
```
super(TransformerDEQModule, self).__init__(func, func_copy)
```
for class TrellisNetDEQModule. That not quite makes sense to me. Should that actually be following line instead? 
```
super(TrellisNetDEQModule, self).__init__(func, func_copy)`
```
Thanks for any clarification!

**Comment by jerrybai1995** [comment]
Hi @kevinliang888 ,

Yes, thanks for pointing this out. Actually I should just put `super().__init__(func, func_copy)`, but you are right that it should be `TrellisNetDEQModule`. I have fixed this and made a new push. 👍
